version: "3.9"


services:
  stockfy-postgres-dev:
    image: postgres:12.9
    container_name: letras-postgres
    hostname: letras-postgres
    ports:
      - 8082:5432
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD_TEST}
    volumes:
      - ./sql_files/create_database.sql:/docker-entrypoint-initdb.d/1-create_database.sql
